name: Deploy to Staging (FTP/FTPS)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/plugins/system/offroadseo/**"
      - "src/plugins/system/offroadstage/**"
      - "src/templates/yootheme_offroad/**"
      - ".github/workflows/deploy-staging.yml"

jobs:
  deploy:
  if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip deploy]') }}
    runs-on: ubuntu-latest
    concurrency:
      group: staging-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # FTP/FTPS deploy – tri ciljne putanje
      - name: Upload offroadseo via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STAGING_FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USER }}
          password: ${{ secrets.STAGING_FTP_PASS }}
          protocol: ftp
          security: loose
          local-dir: src/plugins/system/offroadseo/
          server-dir: ${{ secrets.STAGING_DOCROOT_RELATIVE }}/plugins/system/offroadseo/
          dangerous-clean-slate: true
          log-level: verbose
          timeout: 120000

      - name: Upload offroadstage via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STAGING_FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USER }}
          password: ${{ secrets.STAGING_FTP_PASS }}
          protocol: ftp
          security: loose
          local-dir: src/plugins/system/offroadstage/
          server-dir: ${{ secrets.STAGING_DOCROOT_RELATIVE }}/plugins/system/offroadstage/
          dangerous-clean-slate: true
          log-level: verbose
          timeout: 120000

      - name: Upload YOOtheme child via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STAGING_FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USER }}
          password: ${{ secrets.STAGING_FTP_PASS }}
          protocol: ftp
          security: loose
          local-dir: src/templates/yootheme_offroad/
          server-dir: ${{ secrets.STAGING_DOCROOT_RELATIVE }}/templates/yootheme_offroad/
          dangerous-clean-slate: true
          log-level: verbose
          timeout: 120000
