name: token-check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Show repo via GitHub API (curl)
        run: |
          set -e
          echo "Who am I?"
          curl -s -H "Authorization: token ${{ github.token }}" https://api.github.com/user | jq -r '.login'
          echo "Repo:"
          curl -s -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }} | jq -r '.full_name'
